export {default as Nav} from "./Nav"
export {default as Hero} from "./Hero"
export {default as Skills} from "./Skills"
export {default as Expercience} from "./Expercience"
export {default as Project} from "./Project"
export {default as Education} from "./Education"
export {default as Contact} from "./Contact"
export {default as Footer} from "./Footer"